### ISSUE TITLE
Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.

### ISSUE THREAD

**Issue by iperezx** [QF-Error-Tracking/QFVD5#12]
**Describe the bug**
Error: Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.

Not sure what triggers it and it is random of when it does occur.
Usually I just retry the simulation and the bug doesn't show up again (sometimes I have to retry multiple times).

I made a comment about this bug before, but wanted to report it again since its triggering failures for us (3/36 for a new studhorse ensemble).

**To Reproduce**
Link: https://swat.sdsc.edu/nc/s/NT6RRbmZi9PPSXd
File: run_d2853129-81f8-47a2-ad7e-317a1430ee48.zip
I can provide the rest of them if they are needed.

**Desktop (please complete the following information):**
 - QF Version v5.1.0 + davids new patch (sent via email) or just v5.1.0
 - OS: linux

**Comment by sbrambilla** [comment]
Can you send me the project? The link is psw protected.

**Comment by sbrambilla** [comment]
I cannot seem to be able to reproduce the error after modifying QU_simparams with the missing input.

**Comment by iperezx** [comment]
@sbrambilla 

Do you think it will be worth sending the version of QF we compiled? 

Or the Dockerfile so you can exactly have the same env that we have so you try to reproduce the error?

Do you change the compiler flags from what you guys set as default?
On what operating system are you running this on?

**Comment by sbrambilla** [comment]
I'm not familiar with Dockerfile. Is that like a virtual machine? I think this would be the best option in that case.
I usually run on Mac and Windows but also have Red Hat available. 

Do you have our sh file to compile? Can you try the debug version (or use those flags in your environment)? 

Which version of gfortran do you use? Do you have the intel compiler available (ifort)?

**Comment by iperezx** [comment]
Docker -> https://docs.docker.com/get-started/

Let me send you the dockerfile with instructions via email.

Yes we have all of QF src files. I compile QF with the default flags you guys set in `adv_compile_and_run.sh` so it is in the debug version.

GNU Fortran (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

I can get a hold of one, but when running the big ensembles on our heterogenous cluster, we will not always have one available for all the runs. Why do we need an intel compiler?

**Comment by iperezx** [comment]
Re-ran an uniform fuels ensemble with v5.1.1 and the FPE doesnt appear anymore when compared to v5.1.0 (with David's wind fixes)

Need to test it with the ensemble I initially reported.
