### ISSUE TITLE
QFVD-520 Line Fire example not running

### ISSUE THREAD

**Issue by zacharycope0** [QF-Error-Tracking/QFVD5#15]
**Describe the bug**
QFVD-520 crashing when running LineFire example (QF_5.2.0/samples/LineFire). Error message below.

**Desktop (please complete the following information):**
 - QF Version: 520
 - OS: Ubuntu

**Screenshots**
![image](https://user-images.githubusercontent.com/43671145/220458253-97ebc9e1-aea8-4673-94ab-664ae04fd22c.png)

**Comment by drobinson6045** [comment]
I need to send out a hot fix for this issue.  I'll send one out tonight.  Only happens for flat terrain.  Emailing you the fix for it right now.
