### ISSUE TITLE
Flame.csv: Large File in Output Folder

### ISSUE THREAD

**Issue by zacharycope0** [QF-Error-Tracking/QFVD5#16]
**Is this file necessary? Is it being output on purpose?**

I just noticed that **QF_5.2.2** builds a large file in the output called flame.csv. I don't see it mentioned in the QUIC-Fire_outputs.pdf documentation.

It came to my attention because my test simulations are very small, and these output files are huge:
- For a 600s simulation on a 180x180m domain, flame.csv was **5GB**. 
- For a 600s simulation on a 360x360m domain, flame.csv was **28GB**.

**Comment by sbrambilla** [comment]
Nope, it was meant for debugging and was left in the code I pushed by mistake.

**Comment by zacharycope0** [comment]
Gotcha. Thanks for the quick response.

@drobinson6045 would you be able to patch this bug and push out QF-5.2.3 to the QF users? The flame.csv file is making QF-5.2.2 unusable for bigger simulations. I built a 2-TB .csv over the weekend!

**Comment by sbrambilla** [comment]
@drobinson6045  I have pushed a version without that bug.

**Comment by drobinson6045** [comment]
Distributed version 5.2.3 with the hotfix fixing this issue.
