### ISSUE TITLE
"Number of Ignitions" not working as expected

### ISSUE THREAD

**Issue by zacharycope0** [QF-Error-Tracking/QFVD5#21]
**Describe the bug**
While running tests for Issue #20, I noticed the following:

For a 60s simulation with a 1000m ignition line, when I set the Number of **Ignitions to 2** the head fire develops much faster than when I set the number to **100**. The behavior may result from me placing my initial ignition at the edge of the domain. Another thought was that the strong plume from the initial 100 ignitions caused entrainment that prevented the head fire from spreading as quickly.

Do you think this difference in fire behavior is the result of a bug or based on how my run is set up?

**Desktop (please complete the following information):**
 - QF Version 523
 - OS: Ubuntu

**Screenshots**

*Number of Ignitions = 2*
![image](https://github.com/QF-Error-Tracking/QFVD5/assets/43671145/92d59f4b-f2ae-4d59-b700-fc164706ee20)
![image](https://github.com/QF-Error-Tracking/QFVD5/assets/43671145/a5a20689-7a0e-4d94-8306-3355bf460cf6)

*Number of Ignitions = 100*
![image](https://github.com/QF-Error-Tracking/QFVD5/assets/43671145/516a7947-3fcd-47ba-a1d8-9a87868a30dd)
![image](https://github.com/QF-Error-Tracking/QFVD5/assets/43671145/95393c85-7cf3-4350-b12e-c58776ebe099)

**Comment by zacharycope0** [comment]
I will rerun and print winds to see its may be plume/entrainment related.

**Comment by drobinson6045** [comment]
Your intuition on entrainment is right.  I demonstrated this when the ignition change was initially pushed.  As the ignition count gets larger a greater amount of fuel is combusted initially.  This creates stronger plumes leading to stronger indrafts.  The effect is more obvious in cases like this where a large fireline is ignited instantaneously.

**Comment by zacharycope0** [comment]
@drobinson6045. Thanks for the reply. I'll show the group on Wednesday to remind others to be aware of this dynamic.
