### ISSUE TITLE
TEST_FOR_DAVID-FDRS_QF_Simulation_Time 

### ISSUE THREAD

**Issue by zacharycope0** [QF-Error-Tracking/QFVD5#23]
**TEST:FDRS_QF_Simulation_Time **
David, 
As we discussed in the FDRS meeting today, I would like to test the following simulation to see if there are noticeable differences in simulation times across machines/why the QF sims are taking so long on Matt Jolly's Server. I cut the simulation times 600s and have them running on 1 thread. Please run with QF_523.

I'm currently running the tests on MJs server. I will report the run times in the comments.

**To Reproduce**
Test 1 (Low Wind & High Fuel): https://drive.google.com/file/d/12dbuPQ84XLi_O2ujBN9ISIlF6oy6tibD/view?usp=drive_link
Test 2 (High Wind & Low Fuel): https://drive.google.com/file/d/1jXwZfJ7ypoBTlGJuwAZ275zVK8rmXONl/view?usp=drive_link

**Comment by zacharycope0** [comment]
As David and I discussed in the QF meeting, it seems like these simulations are taking a long time because of the long fireline and QF's plume protocol. I do not believe the long run times have to do with the server I'm running them on.

@drobinson6045. Can you confirm that your runtimes are similar to mine?

<html>
<body>
<google-sheets-html-origin><style type="text/css"></style>

  | Scenarios |  
-- | -- | --
  | Low Wind & High Fuel | High Wind & Low Fuel |  
USFS Workstation (1-Thread) |   |   |  
Simulation time (s) | 75345 | 89778 |  
Sub time fire (s) | 408 | 622 |  
Sub time plumes (s) | 62812 | 77081 |  
Sub time mass-consistency (s) | 11805 | 11745 |  
Bigfire Server (1-Thread) |   |   |  
Simulation time (s) | 64300 | 79972 |  
Sub time fire (s) | 459 | 608 |  
Sub time plumes (s) | 53852 | 69419 |  
Sub time mass-consistency (s) | 9755 | 9681 |  
Bigfire Server (8-Thread) |   |   |  
Simulation time (s) | 20380 | 20080 |  
Sub time fire (s) | 1630 | 1520 |  
Sub time plumes (s) | 16383 | 16234 |  
Sub time mass-consistency (s) | 2133 | 2069 |  


</body>
</html>

**Comment by drobinson6045** [comment]
Definitely the plumes are the slowdown in this case.  We have some ideas to improve the scaling of the algorithm and I hope that it will get addressed sooner than later.  We have very similar timings:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/drobinson/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/drobinson/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">
<meta charset=utf-8>



  | Scenarios |  
-- | -- | --
  | Low   Wind & High Fuel | High   Wind & Low Fuel
MacbookPro   (1-Thread) |   |  
Simulation   time (s) | 64038 | 63185
Sub time fire   (s) | 280 | 381
Sub time   plumes (s) | 59237 | 58621
Sub time   mass-consistency (s) | 4376 | 4016



</body>

</html>
