### ISSUE TITLE
Outputs: Not Seeing Fuel Second Vertical Layer

### ISSUE THREAD

**Issue by zacharycope0** [QF-Error-Tracking/QFVD5#27]
**Describe the bug**
I was running sims to analyze fire behavior in a shrub layer but I'm not seeing any fuel in the output's second vertical layer. 

My treesrhof.dat file has a bulk density 0.5 in the first layer and 0.8 in the second layer. The plots of the output files match the input for first vertical layer but have values of zero for the second vertical later. I don't think made any mistakes with the inputs. I checked gridlist and QUIC_fire.inp to make sure my fuel grid matched the inputs.

Input 1st Vertical Layer:
![plot](https://github.com/QF-Error-Tracking/QFVD5/assets/43671145/e4d1879e-80c2-427f-9eee-1e8ae22f6324)

Input 2nd Vertical Layer:
![plot](https://github.com/QF-Error-Tracking/QFVD5/assets/43671145/44e9d152-1c33-4eb5-ae39-77479b01eed9)

Input 1st Vertical Layer:
![fuel_dens_Time_0_s_Plane_1](https://github.com/QF-Error-Tracking/QFVD5/assets/43671145/f3654779-e99e-4923-9d10-14726d6c3eba)

Input 2nd Vertical Layer:
![fuel_dens_Time_0_s_Plane_2](https://github.com/QF-Error-Tracking/QFVD5/assets/43671145/2078acd5-a1b2-46ea-a630-de6b427c813a)

**To Reproduce**
https://drive.google.com/file/d/1GYxgDLMM8VKET9NAdkylE5IQuRMZ9Ub3/view?usp=share_link

**Desktop (please complete the following information):**
 - QF Version: 531
 - OS: Ubuntu

**Comment by zacharycope0** [comment]
@ntutland. Do you mind double-checking the input files and running this simulation to confirm the bug? I'm very confused by this and want to make sure human error isn't involved.

**Comment by ntutland** [comment]
Sure no problem

**Comment by ntutland** [comment]
@zacharycope0 I am seeing the same thing. Are you using drawfire to plot the outputs? The plotting of horizontal slices in drawfire is defined by "plane"s, which seem to be 1-indexed, so I assume somewhere `plane-1` is used to index the z-layers, but I can't find where. Do you think that could be part of the problem or are you pretty confident in those output plots?

**Comment by zacharycope0** [comment]
@ntutland. Yeah, plane 2 is Python index 1 (the shrub layer). I'm using drawfire's import routine, but I looked at the outputs as numpy arrays and they have the shape and surface fuel I expect. Just no fuel in the second layer.

**Comment by zacharycope0** [comment]
@drobinson6045 do you mind taking a look at this when you get a chance?

**Comment by zacharycope0** [comment]
David found the issue

**Comment by ntutland** [comment]
Is it specific to this sim or should we make sure it is not affecting ours?

**Comment by zacharycope0** [comment]
I resent David's email. He found a fix and thought the interpolation error only occurred for very specific sims: "I believe it just happened to be the case when you import custom fuels that are only 2 layers but I’m not absolutely certain at this point", David.
