### ISSUE TITLE
Getting an Error When Using Flag 5 to Import Dats

### ISSUE THREAD

**Issue by zacharycope0** [QF-Error-Tracking/QFVD5#31]
**Describe the Issue**
David, I'm finding that my FDRS simulations are crashing when I use the 5 flag to import my self-made rhof and moisture .dat files. However, they run when I use a flag of 4. Do you have an idea of why this might be?

**To Reproduce**
https://drive.google.com/file/d/1YS_0B3yzZPd-kmLZ1r4V11m4CIwWB2rZ/view?usp=drive_link

**Desktop (please complete the following information):**
 - QF Version: 600 (was also an issue with ver 5)
 - OS: Ubuntu

**Screenshots**
![image](https://github.com/QF-Error-Tracking/QFVD5/assets/43671145/048267ad-7ea1-4052-b768-1d37aaa002d2)

**Comment by drobinson6045** [comment]
Found the issue.  Logic for determining when to read gridlist was only set up for when interpolation was needed. For now just use option 4 as it results in the same fuels.  This will work correctly with the next release.

Note when using the fastfuels option the header option needed changing (from 1->2) to read correctly with the inputs you were using.

**Comment by zacharycope0** [comment]
@drobinson6045. Sounds good. Thanks for looking into this!
