### ISSUE TITLE
Wind calculations

### ISSUE THREAD

**Issue by iperezx** [QF-Error-Tracking/QFVD5#4]
@zacharycope0 
I have noticed that the wind process in QF is pretty fast when I set the omp threads > 1.

This section in the logs (for reference):
```
Calculating winds for 03/06/2017 10:00:00
Finished interpolating winds
```

You guys mentioned in one of our meetings that we can recycle winds for some ensembles with a new feature that was added in QF recently. Can you elaborate on how to setup QF to recycle Winds?

**Comment by drosales95** [comment]
Hey Ismael!

I just tested it right now and it's broken in the current version (5.0.2). It looks like the flag was read in correctly but the call to generate the startup files is missing. Tagging @sbrambilla and @(david?) for more clarification.

![image](https://user-images.githubusercontent.com/29068635/199769268-2cb528a1-cc03-44f1-88a4-93b7c28b2c2a.png)


The intended sequence would be:
To create the startup files, you would need to do an initial run with the generate startup files flag in QU_fileoptions.inp set to 1. In future runs, you can set that to 0.

To use the startup files, you would change the input flag in QU_metparams to 5 and list the startup files afterwards. There should be one for every wind shift. 

I've attached the files that you would adjust and the form to do so here.
[QU_windstartups.zip](https://github.com/QF-Error-Tracking/QFVD5/files/9930738/QU_windstartups.zip)

**Comment by sbrambilla** [comment]
Daniel,


We're on travel. I'll test it out but may have to get back to you next week.


Sara

________________________________
From: drosales95 ***@***.***>
Sent: Thursday, November 3, 2022 9:59 AM
To: QF-Error-Tracking/QFVD5
Cc: Brambilla, Sara; Mention
Subject: [EXTERNAL] Re: [QF-Error-Tracking/QFVD5] Wind calculations (Issue #4)


Hey Ismael!

I just tested it right now and it's broken in the current version (5.0.2). It looks like the flag was read in correctly but the call to generate the startup files is missing. Tagging @sbrambilla<https://urldefense.com/v3/__https://github.com/sbrambilla__;!!Bt8fGhp8LhKGRg!G6ilDKKBsuHUPI2wdLDh-DoA1CgIcwv2Qj-dyNYu7f4PjpNHBcCibtP1NXshgHPlR4zmb3ICRZKKBzVRpxm0-D58H9E$> and @(david?) for more clarification.

[image]<https://urldefense.com/v3/__https://user-images.githubusercontent.com/29068635/199769268-2cb528a1-cc03-44f1-88a4-93b7c28b2c2a.png__;!!Bt8fGhp8LhKGRg!G6ilDKKBsuHUPI2wdLDh-DoA1CgIcwv2Qj-dyNYu7f4PjpNHBcCibtP1NXshgHPlR4zmb3ICRZKKBzVRpxm0b3B4hk0$>

The intended sequence would be:
To create the startup files, you would need to do an initial run with the generate startup files flag in QU_fileoptions.inp set to 1. In future runs, you can set that to 0.

To use the startup files, you would change the input flag in QU_metparams to 5 and list the startup files afterwards. There should be one for every wind shift.

I've attached the files that you would adjust and the form to do so here.
QU_windstartups.zip<https://urldefense.com/v3/__https://github.com/QF-Error-Tracking/QFVD5/files/9930738/QU_windstartups.zip__;!!Bt8fGhp8LhKGRg!G6ilDKKBsuHUPI2wdLDh-DoA1CgIcwv2Qj-dyNYu7f4PjpNHBcCibtP1NXshgHPlR4zmb3ICRZKKBzVRpxm0yIg6kF0$>

**Comment by drobinson6045** [comment]
This should be working now with version V5.0.3. Let me know if it's not working for you.

**Comment by zacharycope0** [comment]
I'm closing this issue. @drosales95 @iperezx  please reopen if you are still experiencing this issue with V5.0.3
