### ISSUE TITLE
Streaking Head Fire in Light Wind

### ISSUE THREAD

**Issue by zacharycope0** [QF-Error-Tracking/QFVD5#5]
**Describe the bug**
There is almost not flanking fire and the head fire splits into multiply streaks for the following simulation:
Fuel Load = 0.5
FMC = 2.5%
Fuel Depth = 0.5
Wind Speed = 3

**To Reproduce**
https://drive.google.com/file/d/1N2jxdJM3soWqXQdawgQeC4b1O-E7_kHq/view?usp=sharing

**Desktop (please complete the following information):**
 - QF Version QFVD5.0.2
 - OS: Ubuntu 18.04

**Screenshots**
![fuel_dens_Time_3500_s_Plane_1](https://user-images.githubusercontent.com/43671145/200889635-2abd15c9-f3d8-4c94-babe-08c40442d243.png)

**Comment by drobinson6045** [comment]
What was the version where this was ran giving typical headfire shapes?

**Comment by zacharycope0** [comment]
V401

**Comment by drobinson6045** [comment]
@zacharycope0 Can you attach some plots of the old behavior you were seeing?

**Comment by zacharycope0** [comment]
@drobinson6045 Sure thing. By the way these examples all have homogenous FMC of 2.5%.

V4.0.2:
![fuel_dens_Time_7200_s_Plane_1](https://user-images.githubusercontent.com/43671145/200947748-1e9d17fe-73b2-4389-aabe-1a18c7389116.png)

**Comment by drosales95** [comment]
Hey all,

After running a similar testcase on my end I have found fairly simlar results. To be clear, I did not use DAT files for these runs but instead use the homogeneous fuel flags in QUIC_Fire.inp.

Fuel Density: 0.5, FMC: 0.025, FH: 1
![bw_perc_mass_burnt_Time_300_s](https://user-images.githubusercontent.com/29068635/201717649-55e2ba26-e339-419b-bcef-11d9a2420a45.png)

Note that the fire is not spreading in the flanks and backing side of the fire. I will do a similar run lowering the height through the DAT files and report back.

@sbrambilla , do you know if there are any default parameters in the alpha2, or omegarelax or creeping fire that could be causing this?

**Comment by sbrambilla** [comment]
@drosales95 
That has been the behavior for a while (no back spread). It has to do with a variable in the creeping. I think you should talk to him, because he was surprised by the value we're using now, so maybe he was doing some tests and forgot to change it back.

**Comment by drosales95** [comment]
Thanks for the quick response, Sara! @drobinson6045 , tagging you in here as well.

**Comment by zacharycope0** [comment]
Issue not present in 5.1.0
