### ISSUE TITLE
Is QUIC-Fire_outputs.pdf up-to-date?

### ISSUE THREAD

**Issue by iperezx** [QF-Error-Tracking/QFVD5#6]
I dont see all the output variables from [`drawfire.py` ](https://github.com/QF-Error-Tracking/QFVD5/blob/BETA_INPUT_FILES/postprocessing/drawfire.py)
in `docs/QUIC-Fire_outputs.pdf`.  Example: `QF_elevation.bin` , etc.

Is it outdated? I says August 30,2022. So is it for previous versions?

Can we get an up-to-date version that reflects v5.0.0?

**Comment by drosales95** [comment]
Hey Ismael,

Good point. I will work on adding it to the outputs PDF and send you an updated version.

**Comment by drosales95** [comment]
Sara provided us with some updated versions of the docs but it has some files that are not currently being generated. Let me know if you have any questions. 
[QUIC-Fire_outputs.pdf](https://github.com/QF-Error-Tracking/QFVD5/files/10024490/QUIC-Fire_outputs.pdf)
[QUIC-Fire_inputs.pdf](https://github.com/QF-Error-Tracking/QFVD5/files/10024491/QUIC-Fire_inputs.pdf)
