### ISSUE TITLE
QF v311 and v502 differences in fire shape and fuel_density for Linefire

### ISSUE THREAD

**Issue by JayCh1** [QF-Error-Tracking/QFVD5#7]
**Describe the bug**
I have run QF v311 and v502 using what appear to be identical fuel, fire start, and winds, and am getting different fire shapes and fuel_density values in the output files

**To Reproduce**
http://35.12.130.8/study/jay/working/qf5/
or
Email: charneyjay@gmail.com

**Desktop (please complete the following information):**
 - QF Version 3.1.1 vs 5.0.2
 - OS: Ubuntu
 - Hardware SPECs [If applicable]

**Screenshots**
png images in the link show:

fuel density at final time
surface uwind at final time
level 10 wwind at final time

**Comment by zacharycope0** [comment]
Jay,

The two QUIC_fire.inp files that you shared will have different fuel densities. When using uniform fuels the fuel height value acts as a scalar. In the V3.1.1 file you have a value of 1 m and for V5.0.2 you have a value of 0.7 m. 

**QUIC_fire.inp V3.1.1**

![image](https://user-images.githubusercontent.com/43671145/202258684-c33ef84c-af9e-4a99-97e2-460075c333aa.png)

**QUIC_fire.inp  V5.0.2**

![image](https://user-images.githubusercontent.com/43671145/202259238-44e3d305-4974-4acc-b444-5bc1dc2b9af5.png)

I'm going to close this issue. Please reopen if your still seeing differences after modifying the input files.

**Comment by JayCh1** [comment]
I changed .7 to 1.0 in the v502 run, and now I get a fire shape that is more continuous. However, the background/unburnt fuel_density is larger but still still quite a bit lower than in the V311 runs. All v502 files have been updated at:

http://35.12.130.8/study/jay/working/qf5/

**Comment by zacharycope0** [comment]
@JayCh1. I tracked down the problem. You set your fire grid height to 2m and your fuel height to 1m. Therefore your cells are half filled with fuel have a bulk density value that is half of what you expected. We typically run the fuel gird cells with a uniform height of 1m. 

![image](https://user-images.githubusercontent.com/43671145/202490816-6c73eb2f-941b-476c-9231-0f7689f6a2e8.png)

**Comment by JayCh1** [comment]
@zacharycope0 This fixed the problem and the fuel density outputs are now consistent with v311. 

Looking at the samples that were distributed with V502 and comparing then with the examples I was using for 311, the LineFire sample is the only 502 sample with the fire grid height set to 2. That's what tripped me up. I also note that the LineFire is the only sample with a Surface DZ of 1.5 in QU_simparams (all the others are 1.0). I'm not sure why that is, but in case it matters in the future I thought I would point that out as well.

Thanks for sussing this out.
