### ISSUE TITLE
Fortran runtime error: Index '0' of dimension 3 of array 'quwinds%u' below lower bound of 1

### ISSUE THREAD

**Issue by iperezx** [QF-Error-Tracking/QFVD5#8]
**Describe the bug**
Not sure if this is a bug or expected behavior for v5.1.0. 

In v4.0.1 we did not did not see the exception.

Exception: 
```
At line 3360 of file QF_5.1.0/src/quic_fire//buoyant_plume.F90
Fortran runtime error: Index '0' of dimension 3 of array 'quwinds%u' below lower bound of 1
```

**To Reproduce**
We had 8 runs that crashed, but going to share with you one:
https://swat.sdsc.edu/nc/s/NT6RRbmZi9PPSXd -> zip file: run_3ba89f7a-add3-4288-85f9-393a7cd66fd7.zip

**Desktop (please complete the following information):**
 - QF Version: v5.1.0
 - OS: linux

**Comment by crawld** [comment]
contact me for nextcloud password

**Comment by drosales95** [comment]
Hey @drobinson6045 ,

We are still seeing this show up even when we modified the TopoInputs to smooth out the terrain. Are there any inputs we should be setting up differently?

**Comment by drobinson6045** [comment]
I'm not sure yet.  I've been trying to recreate the issue but can't seem to get it to happen.  Sorry it's taking a minute.

**Comment by iperezx** [comment]
Ideas/Qs that might be helpful:
1. If you can't reproduce it, maybe it will make more sense to load in the output files that were generated by QF and try to see what could of driven QF to trigger that error (ex: `fuels-dens-*.bin`, etc.).
2. Do you guys have a fault-tolerant mechanism in QF that we can start turning on? Sometimes referred to as a checkpoint restart. If we turn it on, we can give you the exact values that drove QF to trigger that error.

**Comment by iperezx** [comment]
I was sent a fix for the src file that was returning the error. Re-ran the same ensemble and now it is not crashing with that error. So I think you can say that it did fix it.
